logging:
  level:
    com.example.demo: trace

server.error.include-message: always
management.endpoints.web.exposure.include: '*'

miurls:
  database:
    test: "htpps://mibasededatos.com"

spring:
  output:
    ansi:
      enabled: ALWAYS
